### ISSUE TITLE
Stremio app on Amazon Fire TV devices, PS4, PS5 consoles, Apple TV and IOS devices natively

### ISSUE THREAD

**Issue by xman92** [Stremio/stremio-features#1049]
My version of Stremio is 1.6.12 + 1.6.13 for Android, Android TV OS is 10 and 11

**Is your feature request related to a problem? Please describe.**
I need the Stremio application to be on those 5 devices. This app is still not on these devices yet.
**Describe the solution you'd like**
I wish this app were on these different platforms someday.
**Describe alternatives you've considered**
I have been trying my best to ask developers since day 1 to put the Stremio app on all devices that haven't got this application yet.

**Additional context**
Please make it the 5 devices I mentioned in this request. That's all I'm asking. Thank you!

**Comment by jaruba** [comment]
1. requesting for the app to be released on new platforms is not a feature request so you shouldn't create an issue here for it, there is no place to request for Stremio to come to some new platform, if we can do it then we will do it wether someone requests it or not, otherwise we won't 🤷‍♂️ 
2. Stremio coming to a new platform is not always our choice to make, there are platforms that will never accept Stremio in their stores, from the platforms you mentioned, literally none of them will ever accept a full-fledged Stremio app in their app stores due to app store terms or reviewer rules, imagine working a few years to create an app for a platform and seeing them just refusing the app reviews so no user will ever see it

**Comment by Mlig317** [comment]
hate to necro this but is the source open enough for someone else to develop a homebrew application for a console?

**Comment by wkt88** [comment]
hate to necro this but no you moron

**Comment by Mlig317** [comment]
sudo kill this guy
