### ISSUE TITLE
Request for Hisense VIDAA

### ISSUE THREAD

**Issue by marinaaraujo97** [Stremio/stremio-features#1079]
Hello there

**I'd like to request the addition of the Stremio app on the VIDAA OS, for Hisense TVs.**

Thanks in advance for your time.

Best regards!

**Comment by jaruba** [comment]
Requesting for the app to be released on a new platform is not a valid feature request, feature requests are related to apps that have already been released.

There is no dedicated place to request for the app to be released on new platforms because releasing to new platforms is a general primary goal, if the platform is large enough we may attempt to build an app for it, otherwise we may not.
