### ISSUE TITLE
Adjust timing of the Subtitles

### ISSUE THREAD

**Issue by Lamp-Post** [Stremio/stremio-features#11]
Sometimes the timing of the subtitles are a bit off, and this bugs me a lot. So maybe you could implement a feature to adjust the timing of the subtitles?

**Comment by Tbizla** [comment]
afaik this is possible with VLC. But it would be a nice have this option in stremio itself.

**Comment by Ivshti** [comment]
Try clicking on SUB -> "Wrong subtitles". It will give you options for other subs.

**Comment by Lamp-Post** [comment]
I have already tried that, unfortunately none of the subtitle were on time

**Comment by Ivshti** [comment]
Got it, just wanted to find out if this feature was noticeable  or not.

**Comment by Draxler** [comment]
''Wrong subtitles'' could help a lot of times but a lot times it doesn't help.
- It depence what language, because some languages in general doesn't have that manny subs to choose from then other languages.
- it depence from how popular some show or movie is in some country. If not to pupular in some country, then it doens't have that manny subs to choose from. On the other hand, same movie or show could be realy popular in defferent country and there be a lot of subs for that movie or tv show.

In the end that means some users couldn't find wanted subs at all or all found subs could be unsynced. 
That's why **Custom subs** is so essential for Stremio to have and it's cool that now this option is also included with latest update.

But i do think that **Wrong Subtitles** is realy cool addition to Stremio and it could save user a lot of time because it could found corect subs with just 2 or 3 clicks.

Wron

**Comment by Toxicat** [comment]
I support this. A button to move subtitle in time will be very usefull.

**Comment by tomsihap** [comment]
Is this feature in the agenda ? This is a major issue for whomever like me using subtitles. Using VLC to adjust them can help but not completely (Chromecast isn't supported yet in VLC).

**Comment by Ivshti** [comment]
It is on the agenda.

Btw we have Custom subs now, so you may try this before Subtitles Adjust gets implemented

**Comment by romaopedro** [comment]
I would like to have this feature also

**Comment by Ivshti** [comment]
Ok, I'm pushing it to the top part of the agenda, we should have this in one-two weeks in a release

**Comment by rdewolff** [comment]
any news?

**Comment by Ivshti** [comment]
It's implemented in a beta for a while now, but we delayed the beta's release until Monday

You can test it here: http://beta.strem.io
Use G/H to adjust subtitles

**Comment by pateldhruv1993** [comment]
To add to this I'd also like the program to search subtitles using the file hash (something that VLC does using a plugin). I think the source code for this VLC's plugin is available on Git.

**Comment by Ivshti** [comment]
@pateldhruv1993 it does search by file hash. Don't assume that that guarantees correct subtitles :) It doesn't, as subtitles by hash are often wrong

**Comment by AndreYin** [comment]
Has this been resolved? I still get weird timing issues every now and then, but I don't see an option to adjust the delay..

**Comment by romaopedro** [comment]
@AndreYin it's resolved yes, you can use the keys **G** and **H** to adjust subtitles

**Comment by AndreYin** [comment]
@romaopedro nice, thanks!

**Comment by fgsamuel** [comment]
Congratulations to developer team.
You have done a really good job.
Thanks a lot.
