### ISSUE TITLE
Request: Implement distribyted as the torrent client

### ISSUE THREAD

**Issue by arrudagates** [Stremio/stremio-features#159]
**Is your feature request related to a problem? Please describe.**
Kind of a problem, streaming is most times extremely slow and always buffering for me even on fast connections, i think the blame is on the torrenting system

**Describe the solution you'd like**
I saw this project pop up in github and i think this could be a drastic improvement to performance: https://github.com/distribyted/distribyted

**Describe alternatives you've considered**
Another alternative would be to allow tge users to only use the discovery features, piping the magnet link to their clients/players of choice

**Comment by Ivshti** [comment]
it's extremely complicated to replace the torrent system, in other words it's not going to happen

it would help if you could provide more details about your environment so that we can identify why it's slow for you, such as how many peers it connects to (could be a discovery issue indeed) and what's the average speed and how does it compare to the speed of other clients 

you can see detailed stats when you either press D while the player is running or when you go to localhost:11470/stats.json for full detailed statistics

**Comment by TRtomasz** [comment]
closing due to lack of OP activity.
