### ISSUE TITLE
TVOS Application for Apple TV 4?

### ISSUE THREAD

**Issue by ghost** [Stremio/stremio-features#17]
Any plans for a native Apple TV 4 application since we can side load the app onto the device without a developers account.

**Comment by ceuaugusto** [comment]
Any news about this? Thanks in advance!

**Comment by Ivshti** [comment]
Yes, we're going to do an AppleTV app at the end of the year.

We're going to publish it to the store, and it's not going to support BitTorrent-based add-ons.

Add-ons for movies/series without BitTorrent may still be available though

**Comment by ceuaugusto** [comment]
Good to hear this! I was hoping a version with BitTorrent that could be side loaded to the ATV4 (like the Popcorn Time version from this project: https://github.com/PopcornTimeTV/PopcornTimeTV), but this news is also very good! I'm not a programmer, therefore i can't help programming. But if donation is available, I would be very glad helping the project this way!

**Comment by 7mllm7** [comment]
+1

**Comment by CavalcanteLeo** [comment]
+1

**Comment by CavalcanteLeo** [comment]
any news?

**Comment by luigui95** [comment]
Something about it?

**Comment by CavalcanteLeo** [comment]
almost 2 years, and not even an answer

**Comment by MDOBreno** [comment]
Any news about it?!

**Comment by TRtomasz** [comment]
No, there is no news about AppleTV app. I believe there will be no AppleTV app in future. Instead of this we are working on  new Stremio version that will be a web app. So you will be able to play videos using Stremio 5 in Safari on AppleTV

**Comment by CavalcanteLeo** [comment]
UX of an app for TV is completely different

**Comment by MDOBreno** [comment]
Besides, there is no Safari App for TV

**Comment by CavalcanteLeo** [comment]
> Besides, there is no Safari App for TV

there is one app for that:
https://github.com/jvanakker/tvOSBrowser

but certainly Stremio won't work there, bad UX for tvOS

**Comment by candroid-man** [comment]
So what happened here? Did we give up on this?

**Comment by yodaluca23** [comment]
> So what happened here? Did we give up on this?

IKR

**Comment by Hny-B-King** [comment]
+1

**Comment by ghost** [comment]
10 years and nothing...

**Comment by S0ly** [comment]
Still nothing, plex, infuse, jellyfin have apps but not stremio

**Comment by jaruba** [comment]
@S0ly do any of those support torrents? no

it seems funny to me that you all blame Stremio for the lack of progress instead of understanding the Apple mafia issue

Apple is blocking the possibility of such an app, not Stremio

And when faced with the legal obligation of allowing sideloading in EU, Apple chose to respond with malicious compliance (which is to say that they have no intention of complying, and treat their legal obligations with disrespect and greed towards their own interests)

If you would all focus your efforts against Apple, in an attempt to make them more acceptant and less of a mafia, i am sure that from their responses (or lack of) you would understand exactly who the guilty party is on this subject

**Comment by S0ly** [comment]
@jaruba you visibly don't understand what you are talking about

Stremio does not directly stream a torrent, the client is streaming from a server that is streaming a torrent, so its totally possible to have a stremio app...

and saying apple is a mafia is not understanding them, they can do what they do because they are closed and have their own ecosystem, I will not talk about that but you should make some research before saying such things...

**Comment by S0ly** [comment]
there is not only good people or bad people in the world.... if we can have infuse working whit the link inside stremio there is totally no reason for stremio to not work directly whitout infuse

**Comment by jaruba** [comment]
@S0ly or maybe you don't "understand what you are talking about", as I am the dev lead at Stremio, have been working on Stremio for over 8 years and we have dealt with the Apple mafia (and have been refused by their app stores) many times in the past

a full fledged Stremio app supports torrents, when Stremio was released without torrent support to iOS years ago we had a rating of less than 2 on the app store and users swearing at us in the reviews

**Comment by S0ly** [comment]
@jaruba, being at the top doesn't exempt you from being wrong. Now that you have a web app, you should be capable of developing an app that connects to a self-hosted server, enabling content streaming similar to Jellyfin, etc. Regarding Apple's stance, while their restrictions are a factor, technical and legal considerations are also at play. Furthermore, labeling Apple as a 'mafia' may oversimplify the situation.

**Comment by S0ly** [comment]
And to be honest, Apple isn't entirely at fault here. It's worth noting that a significant portion of Stremio users engage in illegal activities, which complicates the situation.

Hating Apple isn't a valid reason for neglecting to find a solution for all Apple users.

**Comment by jaruba** [comment]
@S0ly i disagree, they have been labeled as "malicious compliance" by many (not just us)

as a non-profit we have put a lot of effort in attempting to work on a new iOS/iPadOS app in expectation of their sideloading acceptance, just to see them be a-holes (again, i partially expected it having dealt with them in the past)

let me outline their initial solution to sideloading:
- apple still needs to approve all sideloadable apps and 3rd party app stores
- they want 0.5 usd per each install and per each update made to every single user (unacceptable for a non-profit)

second solution by apple:
- we do not want money from anyone until they pass 1 mil users, after that they want 0.5 usd per each install and each update for each user
- they will allow developers to submit a request to be allowed to download the app from their own site, but they must have at least 1 mil users in the previous year

Stremio currently has over 34 mil users, we will pass 1 mil users in the first weeks, how exactly are we supposed to pay for the users after that for one year to be accepted by them to allow downloads from our site?

you labeling me as "being on top" is (with all due respect) ignorant, as the Stremio team is fighting against all odds with zero income from any user and Apple is acting like a dog that does not want to unclench its teeth from its high monetary gain bone

**Comment by S0ly** [comment]
@jaruba you said yourself in your argument "as I am the dev lead at Stremio" like everything you say is true.

now you have a real point yes apple is costy

so how does jellyfin do ? maybe ask them.

and if money is a problem I think that if we can pay 3 euro a month a RD, we can pay 1 euro for an app that enable us more confort, so why not making a paid app ?

**Comment by jaruba** [comment]
more so, this is not about legality at all, as Stremio is perfectly legal and always was, this is about Apple being a monopoly with unfair rules, playing a political game that does not have the interest of their users in mind at all

**Comment by jaruba** [comment]
1 eur will allow you to install the app and will also allow you to get one update in the first year.. (maybe... because there are also payment gateway fees, taxes and other legal obligations that must be considered from that same 1 eur)

i reserve my right to call Apple a tech mafia due to their decisions, there is no user freedom with Apple, it is all just a political game towards their high profit interests

so how does Plex (& friends) get accepted? it's simple, there is no content, no supported streaming protocol except that of streaming from ur own remote library, you have to buy a server, download ur own content and maintain it, u stream from yourself to yourself, it is similar to having a local library of videos, just that it is remote, Plex is labeled as a "media player" (just like VLC and other video player apps), not as a "streaming platform" (which is what Stremio is labeled as)

**Comment by S0ly** [comment]
@jaruba most apple user get the link in the stremio and send it into Infuse and it works

and personally even 5 euro if its a one time payment I would pay for it, because other alternatives are not good

**Comment by S0ly** [comment]
and making stremio connect to an external server like infuse do whit jellyfin it should work, maybe ask infuse if they want to support stremio like to a partnership or something..

**Comment by jaruba** [comment]
you don't understand, based on Apple's decisions, there is no chance of making any one time payment as a user, they want your money, every month, and Stremio won't see any money from what you pay, there is a higher chance that any attempt at releasing to Apple will cause Stremio to go bankrupt and cease to exist altogether

**Comment by S0ly** [comment]
okay and a partnership whit infuse ? if you cannot do an app can infuse integrate stremio in them ?

**Comment by jaruba** [comment]
chances are that if Infuse attempts it, they will be banned by Apple too

i will presume that this is not the desire of anyone, nor is the possibility of Stremio to stop its existance because of Apple's unfair games

we will continue to wage this war against all odds with Apple, as that is the spirit of Stremio

we do not need people to tell us to support a new device, expanding device support is one of Stremio's top priorities and we will do it anyway

if we ever find a small hole to crawl through to get on their devices, we will use it, even if it may seem implausible at this point

**Comment by yodaluca23** [comment]
> @S0ly i disagree, they have been labeled as "malicious compliance" by many (not just us)
> 
> 
> 
> as a non-profit we have put a lot of effort in attempting to work on a new iOS/iPadOS app in expectation of their sideloading acceptance, just to see them be a-holes (again, i partially expected it having dealt with them in the past)
> 
> 
> 
> let me outline their initial solution to sideloading:
> 
> - apple still needs to approve all sideloadable apps and 3rd party app stores
> 
> - they want 0.5 usd per each install and per each update made to every single user (unacceptable for a non-profit)
> 
> 
> 
> second solution by apple:
> 
> - we do not want money from anyone until they pass 1 mil users, after that they want 0.5 usd per each install and each update for each user
> 
> - they will allow developers to submit a request to be allowed to download the app from their own site, but they must have at least 1 mil users in the previous year
> 
> 
> 
> Stremio currently has over 34 mil users, we will pass 1 mil users in the first weeks, how exactly are we supposed to pay for the users after that for one year to be accepted by them to allow downloads from our site?
> 
> 
> 
> you labeling me as "being on top" is (with all due respect) ignorant, as the Stremio team is fighting against all odds with zero income from any user and Apple is acting like a dog that does not want to unclench its teeth from its high monetary gain bone

Or yall could just make the .ipa and have users sideload it themselves... 🤯

**Comment by jaruba** [comment]
@yodaluca23 only 0.05% - 0.15% (of all users that would normally install) will install it through the (annoyingly complex) sideloading method of an IPA, our intention is to find a method of allowing the app to be installed by the masses (this includes a simpler sideloading method if ever available), not by the minority..

otherwise how can we justify years of work on an app for a few thousand people? i have seen many IPA sideloadable apps die because of lack of developer interest and a low user count, it is a lot of effort for a slow death

as stated, i can personally guarantee that we are always trying to get into the Apple ecosystem, and we have been trying to get into it for many many years

we will never give up as we will always fight for the interests of our users, this is a promise that i can publicly make with confidence, but it needs to also make sense, the current IPA sideloading method is (imo) intentionally made to be very complicated and very limited specifically to demoralize app developers, we cannot accept such terms

**Comment by Dariusthedoggie** [comment]
@jaruba please just release an IPA for the ones that want to sideload it.

**Comment by S0ly** [comment]
And side loading is now available in EU officially supported by Apple

**Comment by utsur0** [comment]
> how can we justify years of work on an app for a few thousand people? i have seen many IPA sideloadable apps die because of lack of developer interest and a low user count, it is a lot of effort for a slow death

@jaruba Got to wonder how Kodi keeps it up to this day then? 

Honestly we'd expect stremio to be buggy on an obscure platform. I mean hell...the Samsung Tizen 5 app is awful and takes 5x the length of time to load any video—but thing is: **_Its still available_** which allows family members to watch content.

...
 **Point is: Having the capability is better than no capability at all.**

**Comment by jaruba** [comment]
> takes 5x the length of time to load any video

@utsur0 use a network cable for that TV, 2019 Samsung TV has a ridiculous wifi card that crushes the download speed

**Comment by bingoxo** [comment]
@jaruba can you reconsider making an ios app especially that sideloading is not as complex as it used to be especially with tools like https://sidestore.io/ https://github.com/SideStore

**Comment by Qwak-btw** [comment]
Even an app for jailbroken/ iPhones with scarlet or an alternative would be good there are no apple rules for people sideloading  with scarlet or e sign

**Comment by charmedsquints** [comment]
There is an app named Yattee on the tvOS App Store which advertises itself as a generic video player; however one of its key capabilities is connecting to Piped or Invidious instances and enabling users to stream ad-free YouTube. 

Perhaps Stremio on tvOS can implement a similar idea (until Apple is forced to implement full sideloading someday)? This could be simple enough for regular users to set up in a few steps.

**Comment by yodaluca23** [comment]
Pretty sure Stremio said they were now working on an Apple TV version

**Comment by han9over** [comment]
> Pretty sure Stremio said they were now working on an Apple TV version

Where did they say that? There is an app on store called vidi which supports stremio addons and doesn’t have torrents. I’m sure users perspectives have changed. It would be nice if stremio does add on based version for iOS and tvOS devices.

**Comment by homeslixe** [comment]
> Yes, we're going to do an AppleTV app at the end of the year.
> 
> We're going to publish it to the store, and it's not going to support BitTorrent-based add-ons.
> 
> Add-ons for movies/series without BitTorrent may still be available though, and would have to be installed through the upcoming web version of Stremio, or the current http://addons.strem.io



2016. This didn’t age well
