### ISSUE TITLE
Details section for selected episode

### ISSUE THREAD

**Issue by seahindeniz** [Stremio/stremio-features#170]
**Is your feature request related to a problem? Please describe.**
Kind of, yes. Sometimes I may need to see the following details about the episodes of a series:
- Air date (it's kind of the most important detail to have it in this feature request)
- Short description about the episode
- Rating (IMDB preferably)

**Describe the solution you'd like**
After clicking an episode title from the episodes list, Stremio can fetch above details from a source, possibly IMDB and then can display a details section can be placed under the episode title
![image](https://user-images.githubusercontent.com/5789670/109334438-c794fe00-7871-11eb-9b67-0e5926c4adf0.png)

**Comment by krishne35** [comment]
And why not give episode info rather than the whole series info while selecting links for an episode on Andorid![Screenshot_20210921-115833.jpg](https://user-images.githubusercontent.com/35328770/134122517-e748cceb-4280-4272-8599-8aec0e567184.jpg)

**Comment by TRtomasz** [comment]
all these data is displayed here
![image](https://github.com/Stremio/stremio-features/assets/40594253/4131333a-989f-4443-8524-523ba5af83ae)

**Comment by seahindeniz** [comment]
Hi @TRtomasz, the show more and the IMDB score is about the show itself in general and it doesn't show the details about the selected episode

**Comment by maxoku** [comment]
I've checked that if I select an episode and click on the "Show More +" it shows the description of the episode. But it still doesn't show air date of the episode anywhere, nor the score for the episode.
I have to agree that is not a valid close. Only a part of the problem was solved, not the full problem. Air date is a very important data to show. Android app shows it, but not the desktop app.
