### ISSUE TITLE
Support for m3u8 Stream on Android

### ISSUE THREAD

**Issue by kooolarpan** [Stremio/stremio-features#172]
Can't play m3u8 streams on Stremio Android. In Desktop version, it works flawlessly. ![IMG_20210301_232740.jpg](https://user-images.githubusercontent.com/33162706/109536357-bc4a0880-7ae5-11eb-9c82-1de06e9e8440.jpg)

**Comment by jaruba** [comment]
@kooolarpan Stremio Android already supports HLS (there are already many addons that use HLS successfully on Android), your issues are of a different nature.

Some streams may play on Stremio Desktop and not Stremio Android (or vice versa) due to the different headers that they send when requesting the streams.

One common header that is of issue is the `User-Agent` HTTP header, which one of the apps sends and the other does not. There is nothing we can do about this though, as the Desktop version uses MPV and the Android version uses VLC (for Android), it is just how these apps choose to communicate with HTTP servers. Depending on how they choose to communicate, some streaming servers can choose to block their requests.

But again, there is nothing that Stremio can do about this, it is a HTTP server issue from the server which serves these streams..

**Comment by kooolarpan** [comment]
Is there any future plans to switch to mpv in Android?

**Comment by jaruba** [comment]
Not that i know of, we chose VLC because it was a more mature project then MPV when it comes to Android.

But the issue here is not the video players themselves, streaming servers should normally support any video player, so the streaming server u are using in particular is blocking these requests intentionally.

**Comment by kooolarpan** [comment]
Would a proxy server act as a workaround?

**Comment by jaruba** [comment]
I would not recommend proxy servers for video, that will most likely kill the proxies.
