### ISSUE TITLE
Request: Integrate SIMKL into Stremio

### ISSUE THREAD

**Issue by coolsudheera** [Stremio/stremio-features#201]
Please integrate SIMKL into Stremio just like Trakt. It will attract more anime lovers worldwide too.

**Comment by jaruba** [comment]
We do not currently have any plans of integrating SIMKL into Stremio. We might in the future, but this is not on the roadmap for now.

**Comment by seun-odebunmi** [comment]
Is it possible to build this as and add-on ?

**Comment by otDan** [comment]
bumping this up, the current simkl api is very simple and the simkl devs are happy to help if anything is unclear, the integration shouldn't even take a day from what they said, so please join the simkl discord and let's make this happen as people would really appreciate just auto tracking and not syncing the watchlist data

**Comment by coolsudheera** [comment]
Awesome, thanks!
Really excited to see the SIMKL auto tracking inside Stremio similar to
Trakt tracking!

**Comment by Azmarine13** [comment]
Any update on this? Is it available?

**Comment by ARHAEEM** [comment]
Is there any update on this?

**Comment by Deepak391** [comment]
Please integrate SIMKL into Stremio... Really Needed!

**Comment by krishus96** [comment]
any update on this?

**Comment by otDan** [comment]
yeah we really need this to not get ignored

**Comment by Amateur-God** [comment]
any update on this would be a cool feature to have

**Comment by edl2** [comment]
Would Love to have simkl integration, it's such a great service

**Comment by npmstart-pray** [comment]
I thought I was the only one who would’ve wanted this!
Please integrate Simkl into stremio!!!

**Comment by mgbotoe** [comment]
Can we please have support for simkl? I didn't even know there was an open ticket for this, will be amazing!

**Comment by xSignificant** [comment]
Please integrate Simkl into Stremio.

**Comment by vivabyte** [comment]
I use simkl for tracking all my shows, movies, anime etc, I would love it if this was integrated

**Comment by Kraphyl** [comment]
Please integrate

**Comment by Goldenfreddy0703** [comment]
I would also like to have simkl integrated with stremio as well cause I use kodi and stremio as well and me and my team are working on intergrating simkl watchlist to our addon during our watchlust recode. Huge thanks to simkl team, you guys are the best!!!!

**Comment by neomanyouth** [comment]
Please do get this added. Ideally 2-way sync!

**Comment by Goldenfreddy0703** [comment]
To help with sync integration. You can use the ID Lookup Method to help convert all Movies and TV Shows into simkl id's. 

https://simkl.docs.apiary.io/#reference/search/id-lookup/get-items-by-id

**Comment by Goldenfreddy0703** [comment]
> There's no need to use Simkl ID for sync, Simkl API accepts any ID including IMDB, TVDB, TMDB, MAL, ANINDB, Title+year

Wait you serious, no way. That's going to make watchlist integration easier for us, Thank you!!!!!

**Comment by TRtomasz** [comment]
Stremio for now will not integrate Simkl or any other service similar to trakt. As trakt currently is the most popular service for synchronization we see very little need to adding another integration for similar service.

**Comment by Simkl-dev** [comment]
> Stremio for now will not integrate Simkl or any other service similar to trakt. As trakt currently is the most popular service for synchronization we see very little need to adding another integration for similar service. We of course might consider adding it in the future.

Hey there,

I get where you're coming from; Trakt was popular when you integrated, so why add another service like Simkl, right? But consider this:

1. **User Choice:** Not everyone uses Trakt. Some folks prefer Simkl for its unique features, UI, or because they've been longtime users. Offering an alternative like Simkl provides your users with more choices.
2. **Most requested by stremio users who moved away from trakt:** Currently adding Simkl is the most requested feature on Stremio.
4. **Healthy Competition:** Relying solely on one third-party service could be risky in the long run. If Trakt has an outage or changes their API term
4. **User Choice:** Not everyone uses Trakt. Some folks prefer Simkl for its unique features, UI, or because they've been longtime users. Offering an alternative like Simkl provides your users with more choices.
5. **Feature Diversity:** Simkl has some features that Trakt doesn't offer, like anime tracking. There's a whole crowd of anime lovers that would appreciate this.
6. **Community Engagement:** If a significant portion of your user base is asking for Simkl integration, it shows that they're engaged and invested in your platform. Listening to user requests can boost community morale and loyalty.
7. **Wider Appeal:** More integrations can make your platform attractive to a broader audience. It's like saying, "Hey, we support how YOU like to do things!"

**Comment by jaruba** [comment]
@Simkl-dev 

> 5. Feature Diversity

This one is against our app development guidelines. Stremio is not VLC and it is also not Kodi, we don't want to have a million settings that users will get lost in. It is a "just works" app that should require little to no configuration in the app itself.

The addon system is built for flexibility, not the app itself.

Until the addon system will support user playback events, this will not be implemented.

We will only officially advertise already established and highly popular services / products, and even from those, few to none if possible.

**Comment by Goldenfreddy0703** [comment]
> This one is against our app development guidelines.

Hey so i understand you guys don't want to have a million settings that users will get lost in and that's totally fine cause you guys could literally just add the simkl authentication to stremio but simkl can be like how you guys imported Trakt. Simkl has all the essentials that Trakt does and it even provides a nice catalog for users who are into movies, tv shows, and anime and you guys could add that to the discovery page. I don't see why this could not be added. I also do not understand how number 5 could be against your app development guidelines. Yes of course stremio is not like vlc, kodi, nor plex but atleast simkl supports there services like trakt does and its great.

Also, when i try simkl for Kodi or Plex, i don't don't even have to change any settings, just authentication and im done. Is that not possible for stremio?

If you guys can give me an update on that, that would be great.
Thank you

**Comment by Amateur-God** [comment]
> Stremio for now will not integrate Simkl or any other service similar to trakt. As trakt currently is the most popular service for synchronization we see very little need to adding another integration for similar service. We of course might consider adding it in the future.

Except relying on one service is bad, what if trakt has another database outage which knocks them down for weeks and loses months of data? Like they did at the end of last year? 

Trakt also has terrible support for Asian shows and anime, one of the reasons I switched over to simkl which has amazing support for them. 

Trakt is not the best service out there for tracking watch history.

**Comment by Amateur-God** [comment]
> @Simkl-dev 
> 
> > 2. Most requested by Stremio users who moved away from trakt
> 
> This is simply not true, it may be the most requested Simkl feature, but it is not the most requested Stremio feature.. most don't even know what Simkl is
> 
> > 5. Feature Diversity
> 
> This one is against our app development guidelines. Stremio is not VLC and it is also not Kodi, we don't want to have a million settings that users will get lost in. It is a "just works" app that should require little to no configuration in the app itself.
> 
> The addon system is built for flexibility, not the app itself.
> 
> Until the addon system will support user playback events, this will not be possible because we will not add it to the app settings.
> 
> We will only officially advertise already established and highly popular services / products, and even from those, few to none if possible.

Simkl requires the same amount of configuration as trakt, so the argument of going against the app development guidelines of being a system that requires little to no configuration is kinda a mute point there because that also means trakt goes against it

**Comment by jaruba** [comment]
It's simple, we are not in the business of advertising services that are not already known as the best in their area of expertise.

There is no particular reason why Simkl should be integrated (and thus officially advertised) and other tracking services should not. To name a few: Tvmaze, TV Time, MyAnimeList. And we have been contacted in regards to them (either by the creators of said services or community developers that wanted to create addons for them) in the past too, the answer is always that this will not be implemented in the app settings.

This doesn't mean that we are ignoring this requirement, to solve such situations the addon system needs to be extended to house a new type of service that may have different requirements, and the community developers can work on integrating such services as addons.

This is a task is already in our queue, but not of high priority. I do wish to see it happen sooner rather than later, but we are extremely busy and tasks are stacking up due to the recent redesign release.

@Simkl-dev With that said you are a developer, so why not take a stab at it too, the relevant repos are: `stremio-core` (rust), `stremio-addon-sdk` (node.js) and `stremio-web` (react)

**Comment by Simkl-dev** [comment]
@jaruba If your main concern is that featuring Simkl auth will look like advertising in your Stremio settings page, you could add a hidden button for Simkl in the settings on a special URL https://www.stremio.com/acc-settings/simkl/. This way, only Simkl members would know it exists and Simkl will be advertising Stremio to its members.

And after that simply push 1 event to mark what the user has watched using https://simkl.docs.apiary.io/#reference/sync/add-items-to-the-history/add-items-to-watched/watching-history

**Comment by jaruba** [comment]
this is not my only concern, development resources and time are limited, we cannot (and should not) offer special treatment to one particular service (except for the case of most popular service in an area)

for all other cases, the addon system should be used (this is why it was built), as that would give everyone the ability to create addons for all sorts of tracking services

the most recent community dev was working on an anilist tracking addon, there are 2 more that worked on myanimelist addons, there are even devs that want to track in imdb, simkl is no different than all these other cases

so until the addon system supports playback events, this won't be possible because we won't add more tracking services within the app settings directly

as stated above, the relevant projects towards addons supporting playback events are all open source if you're in a rush, alternatively, you will need to wait for the task priority queue to reach this particular task so our team can pick it up

**Comment by otDan** [comment]
> this is not my only concern, development resources and time are very limited, we cannot (and should not) offer special treatment to one particular service (except for the case of most popular service in an area)
> 
> for all other cases, the addon system should be used (this is why it was built), as that would give everyone the ability to create addons for all sorts of tracking services
> 
> the most recent community dev was working on an anilist tracking addon, there are 2 more that worked on myanimelist addons, there are even devs that want to track in imdb, simkl is no different than all these other cases
> 
> so until the addon system supports playback events, this won't be possible because we won't add more tracking services within the app settings directly
> 
> as stated above, the relevant projects towards addons supporting playback events are all open source if you're in a rush, alternatively, you will need to wait for the task priority queue to reach this particular task so our team can pick it up

it seems that even with all the requests of services that are potentially more popular than simkl, 
you don't really have it as any priority to create that addon system support. 
I don't see how asking for a simple integration is out of place if that's the state of things as I have also seen as you have reportedm other services that want integration out there and cannot have it and this post has been created over 2 years ago

**Comment by ARHAEEM** [comment]
Just say it, stremio prefer trakt and don't want to add any competitor to
them epically something strong like simkl 💪... As a PRP user of simkl i
will never go with trakt when i use simkl daily with all apps. And to be
honest if stremio didn't add support I don't give a sheet, but just showing
how stremio care to their users even when simkl founder promote them for
free in the server and begging them for give users what they want....

**Comment by Goldenfreddy0703** [comment]
> I don't see how asking for a simple integration is out of place if that's the state of things as I have also seen as you have reported other services that want integration out there and cannot have it and this post has been created over 2 years ago

Honestly I don't see how asking for a simple integration is out of place as well. Its literately just authentication and tracking and that's it. Like i said, simkl can just be integrated like trakt and there would be no confusing settings that you mentioned the other day. If trakt is literately the only tracking service that Stremio has then im kinda a bit disappointment tbh sense trakt has its downsides. I'm not trying to be rude but from seeing where this is going, I see that you guys can't just add a simple authentication for simkl.  

This is an example of how easy it would be and tracking would be a alot easier for you guys if you added simkl especially for mappings. 
![simkl example](https://github.com/Stremio/stremio-features/assets/62456796/b5341256-cbf2-4c70-96ef-6d99c3308e05)

**Comment by jaruba** [comment]
![Screenshot_20230902_191556_Chrome](https://github.com/Stremio/stremio-features/assets/1777923/4da71d75-fa44-4dc9-98b3-d150a15e53b8)
![Screenshot_20230902_191638_Slack](https://github.com/Stremio/stremio-features/assets/1777923/8b682930-a944-4043-adab-ba7102d35c0e)

the task was added some months back (not 2 years ago) when addon dev interest increased for such addon features

i will not participate in a situation where a dev is rallying his community against our decision, the answer has been given and it will be implemented (we make no promises of an ETA)

i am locking this issue due to rallying
