### ISSUE TITLE
iOS version for sideload

### ISSUE THREAD

**Issue by Lion4K** [Stremio/stremio-features#204]
Can you release an ipa for those who can sideload apps and want to have the same features as the android version?

Thanks in advance!

**Comment by TRtomasz** [comment]
Hi,
As i understand you would like to have Stremio IOS version with the same features as Android app. 
Sadly we do not have such version for iOS. Due to apple store terms and rules which does not apps with features like stremio for Android has. Because of this we had to strip iOS app of a lot of functions.

**Comment by Lion4K** [comment]
Yes, i know about apple restrictions, that's why I'm asking for an outside store IPA that can be sideloaded, there's altstore, there's jailbreak, there's enterprise certificates, we have options, but we don't have a stremio version thats fully featured.

**Comment by QNET17** [comment]
Super suggestion!
It would be only to the advantage to offer the APP as "*.ipa" to provide so also all functions.

I could continue to offer the shortened version in the Apple Store, but through your website a full "*.ipa".

Or offer a fully functional IOS app directly via the alternative stores.

**Comment by quzflx** [comment]
Hi, could you provide the sideloadable ipa if it has been developed.
thanks!
