### ISSUE TITLE
Import items into the library from a specific directory

### ISSUE THREAD

**Issue by lets00** [Stremio/stremio-features#24]
Hi people
Currently (in Linux), The stremio imports only movies that are in the download directory. But, in many cases the main directory is on a Portable HD or on a diferent directory.

Could allow items to be added to other directories?

**Comment by Ivshti** [comment]
Usually it scans everything, but since in Linux there's no universal index for the entire FS which we can ask "give me all video files", we can't do this easily.

Of course, setting directories manually should be easy,but instead of implementing an UI for that you can try by adding symlinks to your dirs in Download. I'm not sure if they would be followed, we'll see

Ideally of course we'll have full-index scanning like on Windows and Linux, so that specific directory isn't needed at all

**Comment by TRtomasz** [comment]
closing this as Stremio in current implementation is scaning disks for video files.
