### ISSUE TITLE
Request: allow to set to 1 or 2 seconds too, for when I move using the arrow keys

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-features#248]
Like this:
https://github.com/Stremio/stremio-features/issues/192

Currently we can set it to 3 seconds. Please offer 1 or 2 seconds too

**Comment by jaruba** [comment]
1-2s seek is too short, i see no logical reason to skip for such a short period

**Comment by AndroidDeveloperLB** [comment]
Too short for what?
Very often this is exactly what I need. I miss some word/sentence, so I need to go back a little. Why do you think I need 3 seconds for this, always?
Many video players offer to go back and forward just 1 second. Some even allow to go a single frame (to see frame-by-frame)...
See here for Media-Player-Classic, that instead of choosing from a list, offers 3 types of ways to skip, and allows you to choose exactly (by number) how much to skip for each:

![image](https://user-images.githubusercontent.com/5357526/158345068-b3900b16-5fb7-4457-893c-32a495bd5baa.png)

**Comment by jaruba** [comment]
if u miss a subtitle, while you decide to seek back and actually press the arrow button, you already loose 1-2s just on that

unless you rest your finger on the back button expecting to miss subtitles, you will most probably need 3s seek to see the subtitle you missed, 1-2s is just too small for any useful need

**Comment by AndroidDeveloperLB** [comment]
I didn't talk about subtitles. Not all videos have subtitles, and sometimes the subtitles are wrong or are bad.
I can also miss something visual that was shown, and not something that was heard (example is some sign).

But even if you talk about subtitles, if I've missed the last word of what's currently shown, 1 second is enough. I don't need to hear 1-3 sentences if I've missed just one word.

3 seconds it a lot. Please offer 1 and 2 seconds too, like what's possible on almost all video players out there.

**Comment by Soniflare** [comment]
I actually second this request.  I was just now looking for possibly some kind of add-on that would allow for 1-second skip/rewind because when I want to view a movie, I have to buffer the whole movie and THEN watch it, because it's extremely slow to load due to a VPN I'm using.  For some reason, the movie I was buffering refused to buffer certain individual frames throughout the runtime, and the only way to continue watching was to skip past that frame by either clicking ahead on the playback bar or by pressing forward to skip 3 seconds.  It would've been REALLY nice if I could've just skipped forward by 1 second instead, because I ended up missing some lines and some cooler moments that only last a second or two simply because I couldn't set the skip time to 1 second.

If you could add this feature, I would greatly appreciate it.

Oh and in case you were wondering, the movie I was talking about was Doctor Strange.  Great movie! 👍
