### ISSUE TITLE
Improve cache information and manipulation

### ISSUE THREAD

**Issue by npit** [Stremio/stremio-features#349]
**Is your feature request related to a problem? Please describe.**
a) It's unclear how the cache currently works. E.g. in my settings I have a 2GB cache limit, but the `stremio-cache` folder is 4.1G. 
It would be helpful to clarify if that limit is per-video (which is very unintuitive) or how caching actually takes space.
b) AFAICS there is no way to clear the cache from the UI - I had to google where the cache location is, and delete it manually.

**Describe the solution you'd like**
- More information in the UI: A better explanation of the maximum / current cache disk space used, cache folder location, etc.
- A button to clear the cache from the UI, rather than doing so manually.

**Comment by TRtomasz** [comment]
Cache is cleared automatically once you start watching next video and you have reached the limit. 
If you start playing video that is 40GB it will store whole 40GB on your disk it can't store only 2GB. Limit  is only checked when you start playing another video.

**Comment by frozen905** [comment]
Same problem here. On Android TV devices this is especially problematic. I set my cache limit to 2GB and need it strictly enforced, because it now is sitting at 4.6GB in size, filled up every last free byte on the entire device, and Stremio can't even open anymore because it just crashes back to launcher (I'm guessing due to having 0 bytes free)

What's the fix here?  I don't have anything over 2GB to spare at any time. Will NO CACHING at least truly use 0?

**Comment by Gater73** [comment]
2 years gone by and with 2GB set my stremio cache folder is over 200gb and i bet you i dont just watched a 4k 200gb video file... this is still a issue
