### ISSUE TITLE
Where can i find Cache settings on Stremio Tv box version

### ISSUE THREAD

**Issue by tst0** [Stremio/stremio-features#354]
Where can i find Cache settings on Stremio Tv box version. I'm on android tv. Can't find anywhere

**Comment by yashcodesfuture** [comment]
> There are no cache settings in Stremio for android tv it ahs been removed.

can you please bring it back ? so that people who want to cache can choose it. You can set no cache as default but removing such a great feature isn't a good choice.

**Comment by jaruba** [comment]
@badboybuilds it is a good choice as it caused a lot of crashes, when u run out of hard disk space the app will crash, and caching is not dynamic as you would imagine, a 100gb video needs 100gb fisk space regardless of what max cache size you choose, because simply creating the 100gb file to write to it makes the system reserve that space (even if it does not have it) for the created file, and nvidia shield pro is literally the only android tv device that can host large files, if we get a better solution to this, we will enable it, otherwise it is causing confusion and many crashes
