### ISSUE TITLE
Let us select our timezone/date.

### ISSUE THREAD

**Issue by pateldhruv1993** [Stremio/stremio-features#37]
The calendar currently for people in US is off by 1 day. I'm assuming that is because you're from Europe or something.. I was actually confused till this day about why none of the episodes shown on the day they're supposed to according to the calendar.

P.S I think previous version of the "Board" was better than the current version. Mainly because scroll wheel defaults to vertical scrolling and usually I want to see all the new episodes and not just the ones that I've missed more than one episode. But a different recommendation section is surely helpful for me at least!

**Comment by Ivshti** [comment]
The exact reason for this is because we don't have the exact release hour/minute of tv episodes, but we know the day, and it's marked as midnight by US pacific time. That resolves to one day early in most places. A hack would be to simply set it at the evening (20:00) which I'm thinking of doing until we get a better source for the data.

We are working now on improvement on the Board, and you will see the reason for this change relatively soon when we introduce more things inside of it.

**Comment by pateldhruv1993** [comment]
I don't know if the reason for not knowing air time is the api you're using or something else. But just an FYI, tvdb's api should have that info considering they show that info on their site.

**Comment by Ivshti** [comment]
@pateldhruv1993 the problem should be resolving bit by bit, we changed it to consider the air time from TVDB as well as the air date; should take effect in 3-10 days.
