### ISSUE TITLE
Ability to pause traffic if VPN is not detected 

### ISSUE THREAD

**Issue by jhedfors** [Stremio/stremio-features#371]
On Android TV, there is no built-in VPN kill switch. While there are apps that provide a visual indicator whether VPN is active or not, it is not an ideal solution.

Having a configurable option where you could have all internet traffic paused if no VPN is detected would be very useful.

**Comment by TRtomasz** [comment]
This is outside of scope of the stremio app few moments of googling, this can be achived using different app
https://vpnsafetydot.com/

**Comment by jhedfors** [comment]
If you would have actually read my request, you would have understood that I am already familiar with this solution. It is not achieving the same thing.

**Comment by jaruba** [comment]
@jhedfors such a feature is meant to be added to VPN client apps (and many such client apps do have this feature), Stremio has no configuration for starting a VPN from it's own app settings, thus a VPN kill switch is out of scope for the project (for now, at least)

**Comment by jhedfors** [comment]
@jaruba Thanks for your reply, and to all those that work on this project. Just for clarity, my proposal was not to have Stremio start the VPN, but rather check whether it is active or not.

**Comment by jan-kleks** [comment]
@TRtomasz @jaruba This is a really serious security matter for Stremio users, and could even possibly endanger the whole project’s image. I think that you should definitely re-open this issue, and let me try to elaborate why is that and what jhedfors actually meant.

The problem with VPN kill switches is that **they unfortunately may fail.** BitTorrent users, to avoid troubles when their VPN app stop working as it should, bind their P2P clients to the VPN’s interface — so that, the client would completely stop downloading in such an emergency situation. You can read more about how this works here: https://old.reddit.com/r/VPNTorrents/comments/qishn4/bind_your_torrenting_client_to_your_vpns_interface/ 

And because Stremio includes support for the BitTorrent protocol as well, it is essential, that a setting to bind its connectivity to the VPN’s interface would be added. This setting for an app with BitTorrent is as crucial as HTTPS support for an internet browser… If a Stremio user would get in trouble for downloading wrong files by mistake, they may start with blaming their VPN, but they also (even if it is not this project’s fault directly) might blame Stremio to some extent…

Maybe not as dangerous as in the case of BitTorrent (where you also share files when downloading), various streaming and debrid services may also store your IP address for quite some time. Interface binding support when using external video players with Stremio would also be important.

As jhedfors mentions Android TV (chosen by many Stremio users), in the first post here, it is worth noting that kill switching is not really viable on this OS, so the interface binding option would be especially useful for this system.  You can check the open-source implementation by the BiglyBT client when working with this OS, for example: https://www.reddit.com/r/VPNTorrents/comments/ppmnax/howto_safely_torrent_on_android_with_biglybt/

Also, the app you have linked to @TRtomasz, only shows (with an ugly dot all the time on your screen) that you might have problems with your VPN connection, but your IP would still leak, and your security will be compromised if the kill switch issues appear all of the sudden: https://help.vpnsafetydot.com/kb/vpn-kill-switches-demystified/ 

BTW, you could use this better integration with VPNs as an opportunity to advertise high-quality VPN on Stremio’s website, and earn some additional money for development.

**Comment by de-sawal** [comment]
Yeah, it's the same problem I pointed out in issue #407; a similar implementation to that of some BitTorrent clients where it lets us choose the network interface would be a perfect solution in my eyes.

**Comment by Anuranj-Krishnan** [comment]
I'd also like that feature. Without binding, I'm afraid that someone in my family might use it and get banned. It's easier to implement the feature than convincing the old folks not to use Stremio unless connected to VPN if not in home network. Binding it to certain WIFI BSSID or VPN network solves my issue.

**Comment by slrgt** [comment]
This would be a great feature. I use it on qbittorrent and its perfect for when i forget to launch the vpn
