### ISSUE TITLE
Adjustable cache on android TV

### ISSUE THREAD

**Issue by terrannz** [Stremio/stremio-features#384]
Some sources only have a few seeds, maybe 5 or fewer.
Please add adjustable cache/buffer to the android TV version of the application.
A larger buffer can make up for a source with few and/or unreliable seeds.

**Comment by technout** [comment]
Agreed, there was a cache size option (2GB, 5GB, 10GB) available in version 1.5.9 but this option is missing in newer versions.

**Comment by luizthiagor** [comment]
I'm agree with this subject, because Stremio is very, very good app!

But in Android tv version, needs to have an "Cache size" configuration likes "100Mb, 250Mb, 500Mb, 750Mb or 1Gb" because some movies or series content dont have enough seeds to run smootly.... And if this option exists we can pause the content and wait some minutes to have an more cached size like PCs, it helps to have much better experiences in app when watching content .... Please devs, considerate this great idea.... Is very necessary and dont do impact on some major TV models!

For default , this option can be disabled, but when users like to have more smootly watching in poor seeds content, can enable this cache sizes according to the device we have ...example : 100Mb is not an "giant" size, 250Mb? Or maybe 500Mb ? This can be an "cache until 50% of an Serie episode of 1Gb" for example and, if have poor seeds, the user can be activate this option, open the content, then , pause it , do an little "happy Hour" and return to watch without freezes ....

The app could be have too an option to "Clear Cache" ...users can use it to clean all cached content when have even issue or if necessary to delete The cached content ....

I understand the Stremio team have removed the old "cache" option in stremio Android TV because the majority of Android TVs dont have enough space to use it without issues , but the old Cache option starts in 2Gb , is much space for some TVs? YES ! but my ideia is an little cache sizes and the maximum allowed can be 1Gb ....THIS WILL HELPS A LOT !

**Comment by 0o120** [comment]
Yes, please allow us to change the cache size.

**Comment by mina733** [comment]
Any plans to bring this feature back? We are able to install streamio onto an external flash drive now.

**Comment by nkoroste** [comment]
+1

**Comment by TRtomasz** [comment]
This is not how cache works. If cache is turned on it will need as much space as file takes on disk

**Comment by nkoroste** [comment]
What do you mean? even today you have to save a certain amount of data on disk or ram  in order to play the content. Today that amount is too small (can you share what it is today?) which makes the movie/show lag. 

On my Android TV, if I pause the stream, I can clearly see it's downloading a few MB then stops. If I unpause the stream, it simultaneously plays what it just downloaded/buffered and restarts downloading the second chunk. However, the playback reaches the undownload chunk faster than what actually downloaded which makes the video freeze/buffer. My download speed in this example is ~2.5mb/s and the total file size is ~8gb, though it takes it a few seconds to reach that max download speed because it has to reestablish connection to all the peers from scratch which is the slow part.

**Comment by Kabouik** [comment]
This issue (and #612) are about cache **and** buffer settings. None of those options have been included in the Android apk. I get it that someone misunderstood how cache works, but I don't understand why this resulted in the issue being flagged as completed.

Buffer size is a very central feature that may make Stremio usable or not, depending on sources quality and bandwidth. If the buffer is too small, even preloading a media won't make Stremio usable.

**Comment by smsoylemez90** [comment]
@TRtomasz re open this and then implement this feature please. I have a giant ssd connected to tv and the app now runs off of it. Only thing missing from the app is higher buffer cache or it will constantly pause to buffer. The whole torrent can be cached even on my huge ssd I don’t care the size but it MUST be there.

**Comment by TheRealFame** [comment]
When is this issue being reopened?
