### ISSUE TITLE
Select/adjust subtitles based on audio

### ISSUE THREAD

**Issue by secrecyflag** [Stremio/stremio-features#386]
**Is your feature request related to a problem? Please describe.**
Currently users need to select subtitles while many times they're not in sync.

**Describe the solution you'd like**
Using a speech recognition algorithm, we could know the timestamp of each subtitle by first recognizing the "first speech" in a video and thus knowing when the subtitles starts. This solution would be very effective since most phones today have a speech-to-text ability by some built in app (or not built in), and also in the web we could easily use an API from some service.

**Describe alternatives you've considered**
Currently there are no good alternatives other than what has already been suggested.

**Additional context**
None.

**Comment by 360fun** [comment]
would be great to integrate this: https://subsync.online/en/online.html

there could be a "re-sync" button to start the process

**Comment by jan-kleks** [comment]
@360fun There is also this more recent project which has much more stars on GitHub: https://github.com/smacke/ffsubsync 

Subtitles in another language can also be used for reference, so that also could be added as a feature.

**Comment by jan-kleks** [comment]
Oh, now I think, since most movies (I guess) have some kind of English subtitles embedded, using them as the reference would probably be the quickest way (on the ffsubsync page it says it takes usually less than a second) to fix non-English subtitles sync.

Using audio for syncing takes 20-30 seconds, but it could be used as a secondary option to fix syncing because it still would be usually quicker than looking for/loading external subtitles by hand.

**Comment by 360fun** [comment]
Even better! 😸

**Comment by jan-kleks** [comment]
To sum up, the subtitles’ loading and syncing process could work in this way:

1. if there are embedded subtitles in a preferred language - load those (including forced subtitles)

2. If not - load subtitles with the official add-on
3. If the sub file name does not match  the movie’s file perfectly, automatically sync them with the embedded subs in another language — it should not take much time, and it could fix the subs “just in case”
4. If there are no embedded subtitles provided with the movie at all, and the name of the subs in the preferred language from the add-on does not match perfectly the movie file’s name. Then, if there are add-on subtitles in another language that do match the name — sync the preferred language subtitles with those. It could be another nice “just in case” variant.
5. If the subtitles are still out of sync, let the user sync them to the audio. It takes longer than syncing to other subtitles, but it still should be relatively quick
6. In rare cases when the subtitles are still not synced, and as the last resort, let the users use the manual syncing slider, or to load the subs from an external file  

If you have any other/better ideas, please share them! Maybe we could finally solve the sub syncing issues once and for all…

**Comment by NoSpamMaam** [comment]
This would be much appreciated

**Comment by TRtomasz** [comment]
This is not possible to implement as this technology is highl experimental. It would not be beneficial to implement not tested feature in stremio

**Comment by alkis04** [comment]
Plex did it and it is useful. I think that having it as an option is always a good idea.

**Comment by kokroo** [comment]
> This is not possible to implement as this technology is highl experimental. It would not be beneficial to implement not tested feature in stremio

It is not experimental at all, there are libraries that implement this very well. This could be tested in the beta versions before being rolled out in the stable channel.

**Comment by ja-irl** [comment]
Any update on this? Anyone working on an add-on? I would love to see this feature in Stremio

**Comment by crnc3vic** [comment]
I'd love to see this feature. +1

**Comment by CorgFather** [comment]
I'd also like to see this feature

**Comment by oriki195** [comment]
Hey everyone,
I’m reopening this issue because the idea is still highly relevant and quite feasible with current browser APIs.

I’m willing to implement a working prototype for automatic subtitle synchronization (based on local audio analysis / VAD) if I get the green light from the core team.

It would be a fully client-side feature - no server or AI model required - just lightweight speech-activity detection and offset/drift correction when a subtitle track is loaded.

If the maintainers are open to it, I’ll start working on a PR.

Thanks!

**Comment by farebyting** [comment]
Bump!
