### ISSUE TITLE
BUG: install on windows 10: no stremio app shortcut created -> no possibility to start program !!

### ISSUE THREAD

**Issue by peefour** [Stremio/stremio-features#43]
Hi

I installed stremio several times under windows 10, but stremio never adds a shortcut (even when option is checked), and there is no trace of the program in the start menu either. Searching for the .exe file yields no results either.

If the program is closed there is NO WAY of starting the program again, only option is a full reinstall just to restart the program.

I suggest to add an option to install stremio under c:/program files (for all users) too.

thanks

**Comment by Ivshti** [comment]
This is a conditional bug, because it usually always adds shortcuts both on desktop and on start menu. The box stops it from adding on the desktop, but it still adds on the start menu.

You can try this installer to solve your own problem: http://dl.strem.io/Stremio%203.6.0.exe

And provide more details about your environment - service pack, exact version of Windows, anti-virus, version, where you downloaded the app from, with which browser - so we can solve the problem in general
