### ISSUE TITLE
Sound out of sync when airplay

### ISSUE THREAD

**Issue by s-dm** [Stremio/stremio-features#46]
I am using strem.io to airplay to Apple TV 4, but I am having trouble with the sound being out of sync. Is there a workaround or is it going to be fixed?

**Comment by Ivshti** [comment]
Does it happen in every single case or only some?

We're familiar with the issue, and it's related to how stremio transcodes to HLS. We're working on the solution, the ETA is about 2-3 months because it's a big project that re-vamps transcoding in general. 

The strange thing is that the same issue doesn't exist with Chromecast, even those we use the same transcoding there.

This is because the Chromecast works around HLS inconsistencies much better than the AppleTV

**Comment by alessandrapereyra** [comment]
Did something happen in this area? I tried on the 4 beta but seems it isn't reading my Apple TV (gen 3). The latest 3.x release still has the out sync issue in all of the videos I tried?

**Comment by TRtomasz** [comment]
Closing this tickat as airplay is no longer supported.
