### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by liqen** [Stremio/stremio-features#49]
Hi, 
I propose develop strem.io with new feature, using https://www.themoviedb.org/ api, so people can search your movies or series and see movies description on own language.

I can help with this.

Thanks for all

**Comment by Ivshti** [comment]
It's a good idea, and it wouldn't take too much to implement, as we already have the international titles in our db and we have our own search engine. So it's a quick job. The problem is, if we also add international titles to the search index, we may get too many false positives for people who search in English, since we also have fuzzy search.
Do you propose anything around that?

**Comment by liqen** [comment]
A fast and effective solution is to activate the API when the language of the stremio is != English. Once the synopses are already in English, and other languages have this problem solved.
What do you think?

**Comment by TRtomasz** [comment]
This can be do done with new tmdb addon configuration
