### ISSUE TITLE
When will you add calendar to Android.

### ISSUE THREAD

**Issue by SFW-ZA** [Stremio/stremio-features#518]
@TRtomasz  as the tile suggest , i see you merging the threads but i cant find an issue that advises if the Calendar will/can be implemented and if its something you are working on for us android users.

I find the calendar usefull when the wife nags for when a show is coming out 

thanks for the work thus far...

**Comment by jaruba** [comment]
There is no such issue, because we have a strong internal rule of never teasing / announcing future features or any ETA. Whenever we do this it gets the users very excited, and they start pressuring us, which makes our job much harder.

Every update, feature, service and new app that is released is always a surprise for the users and never announced prior to release.

**Comment by citkane** [comment]
Sorry to comment on a closed thread, but even though your logic @jaruba is sound and completely understandable, please understand that for users switching from PC to android that the calender is not a new feature. It is more of a huge disappointment that an existing feature is now missing.

In my case, I retired my lumbering HTPC for a tiny efficient Android streaming box, and now have a very unhappy partner who used to LOVE the calender. I am sure that this is a common scenario as many people switch to streaming boxes / modern smart TV's.

Thanks for a awesome product!! (And please bring back the calender soon)
