### ISSUE TITLE
Be Seeder feature

### ISSUE THREAD

**Issue by Vance-ng-vn** [Stremio/stremio-features#626]
**Describe the solution you'd like**
I know that Stremio still seeds while watching videos, but I think that's not enough to stop people from complaining about it killing torrents.

My idea is to create a flag in Stremio's cache storage directory, to mark a specific item not just as a cache, its a seed. It doesn't affect the existing functionality, and it's not necessarily creating a new feature! Of course, there would also be an option to turn content downloaded through the download feature into seeds!

With this additional feature, we would also need a control panel to set features like default ratio, internet speed, deleting seeds, downloading seeds, etc. Clearly, this needs more careful consideration.

And we're close to sending out a message, a guide, so that people know how to use this feature correctly.

**Comment by jan-kleks** [comment]
This is a really fantastic idea to give back to P2P community! However, I think that it might be a good thing to think about the security of users first when torrenting:

- When a user tries to use Stremio’s P2P functionality for the first time, a message could be displayed to tell people that it might be dangerous in some countries without hiding your IP
- A setting to turn off P2P functionality for those who do not want to use it: https://github.com/Stremio/stremio-features/issues/402
- Stremio lacks support for binding to VPN interface which can be especially problematic if you want to seed… I write more about this issue here: https://github.com/Stremio/stremio-features/issues/371#issuecomment-1852796195
- If Stremio would become “too popular” in the future, some drastic measures might be necessary to avoid problems that a video streaming app with “popcorn” in its name had. Like moving the torrenting feature to unofficial add-ons, for instance.

After taking care of security, one could consider even more advanced seeding features such as, for example, seeding content downloaded to “Library” via torrent.

**Comment by TRtomasz** [comment]
Stremio is a streaming platform not a torrent client, this will not be added due to multiple issues.

**Comment by jan-kleks** [comment]
@TRtomasz Even if Stremio is not a torrent client it still supports the protocol. So, if advanced seeding options are out of the question, I implore you to at least look into P2P privacy/security improvements I mentioned in my comment above.

For instance, [this is a classic example where VPN interface binding in Stremio would save people a lot of troubles](https://old.reddit.com/r/Stremio/comments/10l5vwr/no_kill_switch_on_nordvpn_for_firestick/)...

**Comment by Vance-ng-vn** [comment]
@jan-kleks now, im a seeder !

[]()https://github.com/Vance-ng-vn/Stremio-Seeds

**Comment by RokeJulianLockhart** [comment]
@TRtomasz, in the article of yours that is titled “Does Stremio Seed After Closing”, [^1] solely the undermentioned is stated on this topic:

> When you exit player, stremio will close all connections after around 1 minute of inactivity. So there should be no downloading or uploading after all stremio kill it's streaming engine.

I believe that, for me, [^2] and others, [^3] this doesn't sufficiently clarify. If anything, it appears to indicate, to me, that it *does*. Like you, I'd rather it didn't seed, so can you clarify what that article refers to?

[^1]: [`stremio.zendesk.com/hc/en-us/articles/8840369065234`](https://stremio.zendesk.com/hc/en-us/articles/8840369065234-Does-Stremio-Seed-After-Closing#:~:text=Does%20Stremio%20Seed%20After%20Closing?)

[^2]: [`github.com/Stremio/stremio-features/issues/626#issuecomment-3533767446`](https://github.com/Stremio/stremio-features/issues/626#issuecomment-3533767446)

[^3]: [`reddit.com/r/Stremio/comments/ojf5f9/comment/h553ay`](https://www.reddit.com/r/Stremio/comments/ojf5f9/comment/h553ay0/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button#:~:text=Stremio%20does%20seed%20in%20som%20cases.)

If this would be best asked elsewhere, please advise.

**Comment by TRtomasz** [comment]
@RokeJulianLockhart first sentence of the original post says `I know that Stremio still seeds while watching videos` and this is true

**Comment by RokeJulianLockhart** [comment]
@TRtomasz, if you don't mind me asking, is that required for it to function, or for goodwill?

**Comment by Tales-K** [comment]
+1
streamio is tracking mainstream users, enabling seedding would improve torrent community.
Its main function is to consume torrents, why not improve your own content source?
