### ISSUE TITLE
[Addon development] Ability to provide custom loader info

### ISSUE THREAD

**Issue by detarkende** [Stremio/stremio-features#672]
**Stremio Version**
All versions. But this is mostly related to addon development.

**Is your feature request related to a problem? Please describe.**
I'm developing an addon that uses transmission on the addon's server to download the requested torrent (the addon will be self-hostable). Downloading the content with transmission is sometimes a long process, so it would be great if we could indicate the progress to the user.

**Describe the solution you'd like**
The stream handlers could return or point to a streamed text or a websocket connection that indicates the current progress of the stream. The final message would point to the actual media content.

**Describe alternatives you've considered**
- In the `streamHandler`'s response, addons could define a `streams.behaviorHints.progressPageUrl` (or something similar). The app would show a small (for example 300x300px large) `iframe` with the given URL. The addon developer can display the correct progress status. When the progress is done, it can send a `postMessage` from within the iframe to tell the app the final `url` of the stream.
- If the `streamHandler` doesn't provide a `url` or any other source, but provides `{ "behaviorHints": { "progress": 30 }}`, then the app would keep displaying the progress screen and indicate that the current progress is `30%`. Then every `n` seconds, it would requery the same endpoint, until the addon doesn't provide a valid stream source.

**Additional context**
I don't consider myself good at designing such apis, so the above ideas are completely up for debate of course.

**Comment by jaruba** [comment]
well, the issue here is that Transmission does not provide a streaming URL that can be used during the file downloads, this has been a feature request for Transmission since at least 2011

if they would provide such a streaming URL nothing from what u mentioned would be needed at all..

if ur intention is long time seeding, u could use the Stremio Server to initiate the download and get a streaming URL, passing it to Stremio to start playing , then monitoring the active engines in the server, and somehow passing the torrent and download location to Transmission (or any other torrent client) to just continue seeding

there is a project that exports the Stremio cache to qBittorrent, for example: https://github.com/Vance-ng-vn/Stremio-Seeds/

**Comment by detarkende** [comment]
@jaruba thank you for your response. I thought about the best way to move forward. 

I still believe it might be a nice feature for add-on developers to have a progress bar (for other use cases as well), but I understand how difficult it must be to design and create this. Huge upfront cost, but very small returns. But maybe in the future if you guys have more capacity, I think we'd really appreciete this. 🙂 

I considered your suggestions and in the end, I am going to send the torrent to the stremio client to download, but I'll also add it to the transmission client as well. It will download it twice, but at the end of the day, that's not a huge problem.
Now I'm dealing with a different issue, but I'll open a different ticket for that.

Thank you for the response and the resources, you guys are the best! 🙂
