### ISSUE TITLE
Better ios app that can atleast be sideloaded as an ipa through official stremio site.

### ISSUE THREAD

**Issue by Tiddiebear** [Stremio/stremio-features#791]
**Stremio Version**
Stremio Version and OS

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vijayvcm** [comment]
@TRtomasz, Just asking out of curiosity.

Why it is marked as completed? Is the app published to the app store or it’s available to sideload?

I don’t see any download option anywhere either in GitHub or Stream website.

**Comment by Tiddiebear** [comment]
> @TRtomasz, Just asking out of curiosity.
> 
> 
> 
> Why it is marked as completed? Is the app published to the app store or it’s available to sideload?
> 
> 
> 
> I don’t see any download option anywhere either in GitHub or Stream website.

Same lol, he just marked as completed without explanation or any links.

**Comment by jaruba** [comment]
i am the dev lead at Stremio, here is a longer discussion on this subject for those that want details: https://github.com/Stremio/stremio-features/issues/17

**Comment by Tiddiebear** [comment]
So like there wont be an .ipa version (does not need apples consent) because u dont want to simply release it as a side project (probably doesnt even require much maintenance once its developed)

Got it.

**Comment by jaruba** [comment]
@Tiddiebear you are taking things out of context and cherrypicking things towards your own interests

it requires a lot of maintenance, Stremio is always changing and unless the app is updated on all platforms it will suffer and may even become completely deprecated and unfunctional

there is no app that will ever not require maintenance, believing that this is the case is either lack of understanding or wishful thinking

it takes years to build an app too, would YOU dedicate this time when you know that a small number of users would ever use it because a greedy company is forcing its (unfair and unjustifiable) rules on app developers?

**Comment by JediMasterino** [comment]
One question, how does Stremio make money if it does at all? I mean if it doesn't make any profit why would you care how many people use the app. Correct me if my understanding is wrong.

**Comment by Tiagomachado02** [comment]
For the great people here that want to sideload an stremio like app, try cine mate! Hope you enjoy :)

**Comment by ihaveanissueguys** [comment]
> So like there wont be an .ipa version (does not need apples consent) because u dont want to simply release it as a side project (probably doesnt even require much maintenance once its developed)
> 
> Got it.

Stremio really confuses me sometimes with their decisions man..

**Comment by TRtomasz** [comment]
As for now there is new stremio app for iOS available right now only through flighttest.
