### ISSUE TITLE
Enable audio passthrough option for Dolby TrueHD and DTS-HD source to AC3/DTS core

### ISSUE THREAD

**Issue by legowtham** [Stremio/stremio-features#812]
**Stremio Version**
Stremio Version: 1.6.9 
OS: Android TV

**Is your feature request related to a problem? Please describe.**
I'm only getting stereo audio in my surround sound because my receiver is not capable of decoding lossless formats like AAC, Dolby TrueHD and DTS-HD, and a lot of movies doesn't have compatible AC3 track. I don't want to use external players since I lose resume capability, continuous playback, and other features.

**Describe the solution you'd like**
A toggle option for audio passthrough of Dolby TrueHD and DTS-HD to compatible AC3/DTS core. Kodi has this option called "Enable passthrough" in their [audio settings](https://kodi.wiki/view/Talk:Audio_settings). Would need something similar.

**Describe alternatives you've considered**
- Tried Tunneled playback but no luck.
- Right now using Kodi is the only option to play the movies with 5.1 surround sound with enable passthrough. But my TV and Kodi doesn't go well together with lower end hardware, and I personally prefer Stremio UI and Kodi interface is too clumsy and hard to use.

Stremio is a god-sent. This is the only feature I'm missing out, would be so happy if this added.

Thanks devs :)

**Comment by TRtomasz** [comment]
This will not be implemented, as not worth the effort considering small team we are.

**Comment by Yahav** [comment]
So basically you're saying Stremio will never have TrueHD/DTS-HD-MA capability?

**Comment by TioBundy** [comment]
Stremio devs!

You have the option of Passthrough in the mobile app, I just deleted the Android TV app from Mi Fire TV Cube, I have installed the mobile version and the interface is not valid for Android TV, but I do passthrough!, the options appear in mobile app!.
Understand that there is no point in that option on phones or tablets and in a version of Android TV is not there! I don't know anyone who has an AVR or a soundbar connected to mobile by HDMI.

PLEASE!

**Comment by GBouerat** [comment]
On Android TV Nvidia shield pro, I switch video player settings from Exo player to libVLC and I got DTS HDMA on my AVR 👍

**Comment by TioBundy** [comment]
> On Android TV Nvidia shield pro, I switch video player settings from Exo player to libVLC and I got DTS HDMA on my AVR 👍

Yes, now that I have a Shield Pro, I can do what you say if I don't get Passthrough, but on Fire OS, specifically Fire Stick or Cube devices, which are widely used, this gives an error.

And the phone app allows you to activate that option which works for the TV app, which still doesn't make any sense since a phone doesn't have the option to use audio passthrough, but as a method you activate it makes it work. It would be a matter of adding that feature to the TV/Android TV app and many users would be happy with that.

The tunneling option doesn't work on Fire OS either.

**Comment by skullytonne** [comment]
Apologies for necroing, have just been fighting with this myself on a Fire Cube Gen 3 attempting to get multichannel LPCM passed through rather than bitstreaming to a receiver. 

In case useful for anyone else, I managed to get this working via the stock Exoplayer by enabling tunnelled playback and **disabling** hardware decoding. With both on I only get stereo 2.0 out irrespective of what format is playing, but with the latter off I can get multichannel LPCM + all the usual HDR profiles showing correctly.
