### ISSUE TITLE
Better Vimu Media Player Integration

### ISSUE THREAD

**Issue by RunAway189** [Stremio/stremio-features#852]
Dear Stremio Team,

I kindly request improved integration with the Vimu Media Player. As you may know, Vimu is one of the best media players available on the Google Play Store, boasting a plethora of features, including correct subtitle display for anime. Currently, the app functions excellently as an external player, allowing me to play all media on my device (a Shield TV Pro 2019). However, there are some features that are currently missing:

-     Episode markers in Stremio
-     Trakt playback synchronization
-     Skipping credits at the end of an episode

Regarding the first point, the Vimu app already has an API that returns viewed statistics, so this should be manageable for Stremio. It would be fantastic to have an "official" support for this player.

Thank you in advance for your attention to this matter. I hope this post reaches you well.

**Comment by jaruba** [comment]
regarding your first point, Stremio does not integrate features for apps that are not widely known and already popular, because it would mean preferential treatment and Stremio is not in the business of advertising / popularising other apps or projects

regardless of Vimu's features, it has 50k downloads on Google Play, while VLC (for comparison) has over 100 million downloads

regarding trakt and skipping features, those cannot be handled by Stremio anyway, they should be requested as Vimu features, not Stremio features

**Comment by TheAymen** [comment]
While you certainly have a point, unfortunately, Vimu Media Player is perhaps the only viable option on many Android TV boxes for a relatively seamless experience.

While the default players work well on phones, when it comes to Android TV (Chromecast with Google TV HD), you will be hard-pressed to find a player that supports .ass/.ssa format subtitles without dropping frames.

The customisation options are nice too.
