### ISSUE TITLE
Torrent addons on ios

### ISSUE THREAD

**Issue by louaizema** [Stremio/stremio-features#90]
Please enable torrent addons on ios.
Or make an ipa version that we can sideload. 90% of persons who are using unjailbroken iphones are sideloading apps.
Please provide an ipa in which we can stream torrents. Am in love with stremio. I really wanna use it on ios when am in a trip

**Comment by Ivshti** [comment]
thanks for the feedback,

but BitTorrent add-ons are tough on iOS for a few reasons:

- Apple is generally very restrictive towards anything bittorrent: last time I checked I couldn't find a single bittorrent client in the app store
- there are technical issues as well, e.g our bittorrent engine is written in javascript, and iOS is generally not friendly towards JIT compiling: see https://stackoverflow.com/questions/5054732/is-it-prohibited-using-of-jitjust-in-time-compiled-code-in-ios-app-for-appstor

Sorry for that.

We are considering providing an alternative build, since we have it working. Unfortunately there are not many ways to distribute it, since all of them require jailbreaking :(
