### ISSUE TITLE
Add MPC-BE to players availables

### ISSUE THREAD

**Issue by diogofr** [Stremio/stremio-features#99]
Hi!
I wanted to use MPC-BE because it's works better playing 4K in my computer.
Then I changed the source code of file server.js to include this player at players availables.

My suggestion is to add this code:
//--CODE_BEGIN--
mpcBe: {
            title: "MPC-BE",
            args: [''],
            subArg: '/sub ',
            timeArg: '/startpos ',
            playArg: '',
            darwin: {
                path: []
            },
            linux: {
                path: []
            },
            win32: {
                path: ['"C:\\Program Files (x86)\\MPC-BE x64\\mpc-be64.exe"', '"C:\\Program Files\\MPC-BE x64\\mpc-be64.exe"']
            }
        },
//--CODE_END--

Best regards,
Diogo

**Comment by maxoku** [comment]
I don't see any option to open in MPC-BE. Is it added?

**Comment by TRtomasz** [comment]
@maxoku yes, it should be working on windows if it is installed in one of these path `C:\Program Files (x86)\MPC-BE x64\mpc-b4.exe"', '"C:\Program Files\MPC-BE x64\mpc-be64.exe`

**Comment by maxoku** [comment]
@TRtomasz I've installed it in a different location, cuz Windows restricts access to Program Files folder and I couldn't save my settings there. Is there a way to enable the player installed in a different location? Manually add the location somewhere?

**Comment by maxoku** [comment]
@TRtomasz Oki I edited file server.js and added the location. The option appeared and opens the player. Problem is that it doesn't work properly. It sent 3 files to the player. First two are invalid, the third contains the video, but doesn't show the duration properly, e.g. showing that video is 26 seconds instead of how it's really long. Though other video opened properly, I mean showing the proper length, the 2 invalid files were still present.

Btw, I'm pretty sure the first location "C:\Program Files (x86)\MPC-BE x64\mpc-b4.exe" is wrong. I think it should be: "C:\Program Files (x86)\MPC-BE x86\mpc-be.exe" or "C:\Program Files (x86)\MPC-BE\mpc-be.exe". I use x64 version, so I can't tell at the moment.
